services:
  - type: web
    name: rent-ledger
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./app/Dockerfile
    dockerContext: ./app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    healthCheckPath: /
